# This is a basic workflow to help you get started with Actions

name: Lint CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  eslint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Runs a single command using the runners shell
      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: code/eslint_report.json
      
      - name: Installing dependencies
        run: npm install
        working-directory: code
        
      - name: Running eslint
        run: npm run lint
        working-directory: code
        
      - name: Saving code linting report to JSON
        run: eslint --output-file eslint_report.json --format json code
        
      - name: Uploading ESLint report
        uses: actions/upload-artifact@v1
        with:
          name: eslint_report.json
          path: eslint_report.json
